Fix build for Scala 2.10
Just use `Console.in.readLine` instead of `StdIn.readLine`

    [error] src/main/scala/codecheck/github/app/CommandRunner.scala:76: object StdIn is not a member of package io
    [error]     Iterator.continually(scala.io.StdIn.readLine).takeWhile { s =>
    [error]                                   ^